import { CityHub, InterchangeTransit, OptimizationMode } from "./types";

export const INDIAN_CITIES: CityHub[] = [
  {
    id: "BLR",
    name: "Bangalore",
    state: "Karnataka",
    airportCode: "BLR",
    airportName: "Kempegowda Intl Airport",
    stationCode: "SBC",
    stationName: "KSR Bengaluru City Junction",
    busTerminalCode: "MJC",
    busTerminalName: "Majestic Central KSRTC Bus Terminal",
    zone: "SWR",
    latitude: 12.977595,
    longitude: 77.568083,
    trainsCalling: 150,
    firstDeparture: "01:30",
    lastDeparture: "23:55",
  },
  {
    id: "DEL",
    name: "Delhi NCR",
    state: "Delhi NCR",
    airportCode: "DEL",
    airportName: "Indira Gandhi Intl Airport (T1/T2/T3)",
    stationCode: "NDLS",
    stationName: "New Delhi Railway Station",
    busTerminalCode: "ISBT",
    busTerminalName: "Maharana Pratap ISBT Kashmere Gate",
    zone: "NR",
    latitude: 28.642314,
    longitude: 77.220004,
    trainsCalling: 233,
    firstDeparture: "00:10",
    lastDeparture: "23:55",
  },
  {
    id: "BOM",
    name: "Mumbai",
    state: "Maharashtra",
    airportCode: "BOM",
    airportName: "Chhatrapati Shivaji Maharaj Intl",
    stationCode: "CSMT",
    stationName: "Chhatrapati Shivaji Maharaj Terminus",
    busTerminalCode: "DDR",
    busTerminalName: "Dadar Asiad Intercity Terminal",
    zone: "CR",
    latitude: 18.944481,
    longitude: 72.836903,
    trainsCalling: 99,
    firstDeparture: "00:10",
    lastDeparture: "23:45",
  },
  {
    id: "HYD",
    name: "Hyderabad",
    state: "Telangana",
    airportCode: "HYD",
    airportName: "Rajiv Gandhi Intl Airport (Shamshabad)",
    stationCode: "HYB",
    stationName: "Hyderabad Deccan (Nampally)",
    busTerminalCode: "MGBS",
    busTerminalName: "Mahatma Gandhi Bus Station (MGBS)",
    zone: "SCR",
    latitude: 17.433147,
    longitude: 78.501481,
    trainsCalling: 227,
    firstDeparture: "00:10",
    lastDeparture: "23:45",
  },
  {
    id: "MAA",
    name: "Chennai",
    state: "Tamil Nadu",
    airportCode: "MAA",
    airportName: "Chennai Intl Airport",
    stationCode: "MAS",
    stationName: "Puratchi Thalaivar Dr. MGR Central",
    busTerminalCode: "CMBT",
    busTerminalName: "Chennai Mofussil Bus Terminus (Koyambedu)",
    zone: "SR",
    latitude: 13.084761,
    longitude: 80.274856,
    trainsCalling: 176,
    firstDeparture: "00:15",
    lastDeparture: "23:45",
  },
  {
    id: "PNQ",
    name: "Pune",
    state: "Maharashtra",
    airportCode: "PNQ",
    airportName: "Pune Intl Airport (Lohegaon)",
    stationCode: "PUNE",
    stationName: "Pune Railway Junction",
    busTerminalCode: "SWG",
    busTerminalName: "Swargate Central Bus Station",
    zone: "CR",
    latitude: 18.529378,
    longitude: 73.873086,
    trainsCalling: 181,
    firstDeparture: "00:10",
    lastDeparture: "23:50",
  },
  {
    id: "CCU",
    name: "Kolkata",
    state: "West Bengal",
    airportCode: "CCU",
    airportName: "Netaji Subhash Chandra Bose Intl",
    stationCode: "HWH",
    stationName: "Howrah Railway Station",
    busTerminalCode: "ESP",
    busTerminalName: "Esplanade Interstate Bus Terminal",
    zone: "ER",
    latitude: 22.584078,
    longitude: 88.341,
    trainsCalling: 283,
    firstDeparture: "01:05",
    lastDeparture: "23:55",
  },
  {
    id: "AMD",
    name: "Ahmedabad",
    state: "Gujarat",
    airportCode: "AMD",
    airportName: "Sardar Vallabhbhai Patel Intl",
    stationCode: "ADI",
    stationName: "Ahmedabad Kalupur Junction",
    busTerminalCode: "GMB",
    busTerminalName: "Gita Mandir Central Bus Port",
    zone: "WR",
    latitude: 23.0225,
    longitude: 72.5714,
    trainsCalling: 238,
    firstDeparture: "00:25",
    lastDeparture: "23:59",
  },
  {
    id: "JAI",
    name: "Jaipur",
    state: "Rajasthan",
    airportCode: "JAI",
    airportName: "Jaipur Intl Airport (Sanganer)",
    stationCode: "JP",
    stationName: "Jaipur Junction Railway Station",
    busTerminalCode: "SCB",
    busTerminalName: "Sindhi Camp Central Bus Station",
    zone: "NWR",
    latitude: 26.9124,
    longitude: 75.7873,
    trainsCalling: 162,
    firstDeparture: "00:01",
    lastDeparture: "23:45",
  },
  {
    id: "COK",
    name: "Kochi",
    state: "Kerala",
    airportCode: "COK",
    airportName: "Cochin Intl Airport (Nedumbassery)",
    stationCode: "ERS",
    stationName: "Ernakulam South Junction",
    busTerminalCode: "VMH",
    busTerminalName: "Vyttila Mobility Hub Bus Station",
    zone: "SR",
    latitude: 9.9312,
    longitude: 76.2673,
    trainsCalling: 158,
    firstDeparture: "00:13",
    lastDeparture: "23:48",
  },
  {
    id: "GOI",
    name: "Goa",
    state: "Goa",
    airportCode: "GOI",
    airportName: "Goa Intl Airport (Dabolim / Mopa)",
    stationCode: "MAO",
    stationName: "Madgaon Railway Junction",
    busTerminalCode: "PNJ",
    busTerminalName: "Panaji KSRTC Kadamba Bus Stand",
    zone: "KR",
    latitude: 15.2993,
    longitude: 74.124,
    trainsCalling: 64,
    firstDeparture: "01:08",
    lastDeparture: "22:50",
  },
  {
    id: "LKO",
    name: "Lucknow",
    state: "Uttar Pradesh",
    airportCode: "LKO",
    airportName: "Chaudhary Charan Singh Intl",
    stationCode: "LKO",
    stationName: "Lucknow Charbagh NR Junction",
    busTerminalCode: "ABT",
    busTerminalName: "Alambagh Multimodal Bus Port",
    zone: "NR",
    latitude: 26.8467,
    longitude: 80.9462,
    trainsCalling: 240,
    firstDeparture: "00:25",
    lastDeparture: "23:55",
  },
  {
    id: "ATQ",
    name: "Amritsar",
    state: "Punjab",
    airportCode: "ATQ",
    airportName: "Sri Guru Ram Dass Jee Intl Airport",
    stationCode: "ASR",
    stationName: "Amritsar Junction Railway Station",
    busTerminalCode: "ASRB",
    busTerminalName: "Amritsar Central Bus Stand",
    zone: "NR",
    latitude: 31.634,
    longitude: 74.8723,
    trainsCalling: 93,
    firstDeparture: "01:10",
    lastDeparture: "23:45",
  },
  {
    id: "BBI",
    name: "Bhubaneswar",
    state: "Odisha",
    airportCode: "BBI",
    airportName: "Biju Patnaik Intl Airport",
    stationCode: "BBS",
    stationName: "Bhubaneswar Railway Station",
    busTerminalCode: "BRMB",
    busTerminalName: "Barmunda ISBT Bus Terminal",
    zone: "ECoR",
    latitude: 20.2961,
    longitude: 85.8245,
    trainsCalling: 179,
    firstDeparture: "00:15",
    lastDeparture: "23:50",
  },
  {
    id: "VNS",
    name: "Varanasi",
    state: "Uttar Pradesh",
    airportCode: "VNS",
    airportName: "Lal Bahadur Shastri Intl Airport",
    stationCode: "BSB",
    stationName: "Varanasi Junction (Cantonment)",
    busTerminalCode: "VNSB",
    busTerminalName: "Varanasi Cantt ISBT Bus Station",
    zone: "NR",
    latitude: 25.3176,
    longitude: 82.9739,
    trainsCalling: 210,
    firstDeparture: "00:20",
    lastDeparture: "23:40",
  },
  {
    id: "AGR",
    name: "Agra",
    state: "Uttar Pradesh",
    airportCode: "AGR",
    airportName: "Agra Kheria Civil Air Terminal",
    stationCode: "AGC",
    stationName: "Agra Cantt Railway Station",
    busTerminalCode: "AGRB",
    busTerminalName: "Idgah ISBT Bus Terminal Agra",
    zone: "NCR",
    latitude: 27.1767,
    longitude: 78.0081,
    trainsCalling: 185,
    firstDeparture: "00:05",
    lastDeparture: "23:50",
  },
  {
    id: "PAT",
    name: "Patna",
    state: "Bihar",
    airportCode: "PAT",
    airportName: "Jayprakash Narayan Intl Airport",
    stationCode: "PNBE",
    stationName: "Patna Junction Railway Station",
    busTerminalCode: "PATB",
    busTerminalName: "Bankipur ISBT Bus Terminal Patna",
    zone: "ECR",
    latitude: 25.5941,
    longitude: 85.1376,
    trainsCalling: 245,
    firstDeparture: "00:10",
    lastDeparture: "23:55",
  },
  {
    id: "GAU",
    name: "Guwahati",
    state: "Assam",
    airportCode: "GAU",
    airportName: "Lokpriya Gopinath Bordoloi Intl",
    stationCode: "GHY",
    stationName: "Guwahati Railway Junction",
    busTerminalCode: "GAUB",
    busTerminalName: "ISBT Betkuchi Bus Station Guwahati",
    zone: "NFR",
    latitude: 26.1445,
    longitude: 91.7362,
    trainsCalling: 140,
    firstDeparture: "00:30",
    lastDeparture: "23:30",
  },
  {
    id: "IDR",
    name: "Indore",
    state: "Madhya Pradesh",
    airportCode: "IDR",
    airportName: "Devi Ahilya Bai Holkar Airport",
    stationCode: "INDB",
    stationName: "Indore Junction Railway Station",
    busTerminalCode: "IDRB",
    busTerminalName: "Sarwate Bus Stand Indore",
    zone: "WR",
    latitude: 22.7196,
    longitude: 75.8577,
    trainsCalling: 110,
    firstDeparture: "01:00",
    lastDeparture: "23:45",
  },
  {
    id: "BHO",
    name: "Bhopal",
    state: "Madhya Pradesh",
    airportCode: "BHO",
    airportName: "Raja Bhoj Intl Airport",
    stationCode: "BPL",
    stationName: "Bhopal Junction (Rani Kamalapati)",
    busTerminalCode: "BHOB",
    busTerminalName: "ISBT Bhopal Bus Terminal",
    zone: "WCR",
    latitude: 23.2599,
    longitude: 77.4126,
    trainsCalling: 260,
    firstDeparture: "00:05",
    lastDeparture: "23:55",
  },
  {
    id: "NAG",
    name: "Nagpur",
    state: "Maharashtra",
    airportCode: "NAG",
    airportName: "Dr. Babasaheb Ambedkar Intl",
    stationCode: "NGP",
    stationName: "Nagpur Junction Railway Station",
    busTerminalCode: "NAGB",
    busTerminalName: "Ganeshpeth MSRTC Bus Stand",
    zone: "CR",
    latitude: 21.1458,
    longitude: 79.0882,
    trainsCalling: 290,
    firstDeparture: "00:01",
    lastDeparture: "23:59",
  },
  {
    id: "IXC",
    name: "Chandigarh",
    state: "Punjab / Haryana",
    airportCode: "IXC",
    airportName: "Shaheed Bhagat Singh Intl Airport",
    stationCode: "CDG",
    stationName: "Chandigarh Junction Railway Station",
    busTerminalCode: "CDGB",
    busTerminalName: "ISBT Sector 43 Bus Stand Chandigarh",
    zone: "NR",
    latitude: 30.7333,
    longitude: 76.7794,
    trainsCalling: 95,
    firstDeparture: "01:20",
    lastDeparture: "23:30",
  },
  {
    id: "STV",
    name: "Surat",
    state: "Gujarat",
    airportCode: "STV",
    airportName: "Surat International Airport",
    stationCode: "ST",
    stationName: "Surat Railway Junction",
    busTerminalCode: "STVB",
    busTerminalName: "GSRTC Central Bus Port Surat",
    zone: "WR",
    latitude: 21.1702,
    longitude: 72.8311,
    trainsCalling: 275,
    firstDeparture: "00:05",
    lastDeparture: "23:55",
  },
  {
    id: "VTZ",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    airportCode: "VTZ",
    airportName: "Visakhapatnam International Airport",
    stationCode: "VSKP",
    stationName: "Visakhapatnam Junction",
    busTerminalCode: "VTZB",
    busTerminalName: "Dwaraka RTC Complex Bus Station",
    zone: "ECoR",
    latitude: 17.6868,
    longitude: 83.2185,
    trainsCalling: 195,
    firstDeparture: "00:15",
    lastDeparture: "23:50",
  },
  {
    id: "CJB",
    name: "Coimbatore",
    state: "Tamil Nadu",
    airportCode: "CJB",
    airportName: "Coimbatore International Airport",
    stationCode: "CBE",
    stationName: "Coimbatore Junction",
    busTerminalCode: "CJBB",
    busTerminalName: "Gandhipuram Central Bus Stand",
    zone: "SR",
    latitude: 11.0168,
    longitude: 76.9558,
    trainsCalling: 135,
    firstDeparture: "00:20",
    lastDeparture: "23:45",
  },
  {
    id: "IXM",
    name: "Madurai",
    state: "Tamil Nadu",
    airportCode: "IXM",
    airportName: "Madurai International Airport",
    stationCode: "MDU",
    stationName: "Madurai Junction",
    busTerminalCode: "IXMB",
    busTerminalName: "Mattuthavani Integrated Bus Terminus",
    zone: "SR",
    latitude: 9.9252,
    longitude: 78.1198,
    trainsCalling: 120,
    firstDeparture: "00:10",
    lastDeparture: "23:35",
  },
  {
    id: "DED",
    name: "Dehradun",
    state: "Uttarakhand",
    airportCode: "DED",
    airportName: "Jolly Grant Airport Dehradun",
    stationCode: "DDN",
    stationName: "Dehradun Railway Station",
    busTerminalCode: "DEDB",
    busTerminalName: "ISBT Dehradun Bus Terminal",
    zone: "NR",
    latitude: 30.3165,
    longitude: 78.0322,
    trainsCalling: 45,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
  },
  {
    id: "IXR",
    name: "Ranchi",
    state: "Jharkhand",
    airportCode: "IXR",
    airportName: "Birsa Munda Airport Ranchi",
    stationCode: "RNC",
    stationName: "Ranchi Railway Junction",
    busTerminalCode: "IXRB",
    busTerminalName: "Khadgara ISBT Bus Stand Ranchi",
    zone: "SER",
    latitude: 23.3441,
    longitude: 85.3096,
    trainsCalling: 105,
    firstDeparture: "00:40",
    lastDeparture: "23:40",
  },
  {
    id: "KNU",
    name: "Kanpur",
    state: "Uttar Pradesh",
    airportCode: "KNU",
    airportName: "Kanpur Chakeri Airport",
    stationCode: "CNB",
    stationName: "Kanpur Central Railway Station",
    busTerminalCode: "KPNB",
    busTerminalName: "Jhajharpur ISBT Bus Station Kanpur",
    zone: "NCR",
    latitude: 26.4499,
    longitude: 80.3319,
    trainsCalling: 320,
    firstDeparture: "00:01",
    lastDeparture: "23:59",
  },
  {
    id: "IXP",
    name: "Prayagraj",
    state: "Uttar Pradesh",
    airportCode: "IXP",
    airportName: "Prayagraj Civil Airport (Bamrauli)",
    stationCode: "PRYJ",
    stationName: "Prayagraj Junction (Allahabad)",
    busTerminalCode: "PRYB",
    busTerminalName: "Civil Lines Bus Stand Prayagraj",
    zone: "NCR",
    latitude: 25.4358,
    longitude: 81.8463,
    trainsCalling: 280,
    firstDeparture: "00:05",
    lastDeparture: "23:55",
  },
  {
    id: "IXJ",
    name: "Jammu",
    state: "Jammu and Kashmir",
    airportCode: "IXJ",
    airportName: "Jammu Airport (Satwari)",
    stationCode: "JAT",
    stationName: "Jammu Tawi Railway Station",
    busTerminalCode: "IXJB",
    busTerminalName: "Jammu General Bus Stand",
    zone: "NR",
    latitude: 32.7266,
    longitude: 74.857,
    trainsCalling: 85,
    firstDeparture: "01:00",
    lastDeparture: "23:15",
  },
  {
    id: "SXR",
    name: "Srinagar",
    state: "Jammu and Kashmir",
    airportCode: "SXR",
    airportName: "Sheikh ul-Alam Intl Airport",
    stationCode: "SRE",
    stationName: "Srinagar Railway Station",
    busTerminalCode: "SXRB",
    busTerminalName: "TRC Bus Terminal Srinagar",
    zone: "NR",
    latitude: 34.0837,
    longitude: 74.7973,
    trainsCalling: 30,
    firstDeparture: "06:30",
    lastDeparture: "19:00",
  },
  {
    id: "TRV",
    name: "Trivandrum",
    state: "Kerala",
    airportCode: "TRV",
    airportName: "Thiruvananthapuram Intl Airport",
    stationCode: "TVC",
    stationName: "Thiruvananthapuram Central",
    busTerminalCode: "TRVB",
    busTerminalName: "Thampanoor KSRTC Central Bus Station",
    zone: "SR",
    latitude: 8.5241,
    longitude: 76.9366,
    trainsCalling: 140,
    firstDeparture: "00:15",
    lastDeparture: "23:45",
  },
  {
    id: "BDQ",
    name: "Vadodara",
    state: "Gujarat",
    airportCode: "BDQ",
    airportName: "Vadodara International Airport",
    stationCode: "BRC",
    stationName: "Vadodara Railway Junction",
    busTerminalCode: "BDQB",
    busTerminalName: "Central Bus Terminal Vadodara",
    zone: "WR",
    latitude: 22.3072,
    longitude: 73.1812,
    trainsCalling: 250,
    firstDeparture: "00:10",
    lastDeparture: "23:55",
  },
  {
    id: "AYJ",
    name: "Ayodhya",
    state: "Uttar Pradesh",
    airportCode: "AYJ",
    airportName: "Maharishi Valmiki Intl Airport",
    stationCode: "AY",
    stationName: "Ayodhya Dham Railway Junction",
    busTerminalCode: "AYDB",
    busTerminalName: "Ayodhya Central Bus Station",
    zone: "NR",
    latitude: 26.7922,
    longitude: 82.1998,
    trainsCalling: 90,
    firstDeparture: "01:00",
    lastDeparture: "23:30",
  },
];

// Configurable minimum connection buffer rules (in minutes) across all modes
export const CONNECTION_BUFFERS = {
  AIRPORT_TO_AIRPORT: 120, // 2h domestic flight-to-flight baggage & gate buffer
  STATION_TO_STATION: 30,  // 30 mins within railway interchange platform
  BUS_TO_BUS: 30,          // 30 mins interchange within bus terminal
  STATION_TO_BUS: 45,      // 45 mins station to adjacent bus stand (e.g. SBC -> Majestic)
  BUS_TO_STATION: 45,      // 45 mins bus terminal to railway station
  AIRPORT_TO_STATION: 150, // 2.5h including airport exit, metro/cab transfer into city center
  STATION_TO_AIRPORT: 180, // 3h including travel, luggage drop, and TSA/CISF security cutoffs
  AIRPORT_TO_BUS: 150,     // 2.5h city transit from airport to interstate bus bay
  BUS_TO_AIRPORT: 180,     // 3h highway buffer + flight check-in cutoffs
  INTER_TERMINAL_AIRPORT: 90,
} as const;

// Realistic intra-city terminal interchange knowledge graph
export const CITY_INTERCHANGES: Record<string, InterchangeTransit[]> = {
  BLR: [
    {
      fromNodeCode: "BLR",
      toNodeCode: "SBC",
      cityId: "BLR",
      mode: "shuttle",
      durationMinutes: 90,
      description: "BMTC Vayu Vajra Airport AC Express (KIA-9)",
      estCost: 260,
    },
    {
      fromNodeCode: "BLR",
      toNodeCode: "MJC",
      cityId: "BLR",
      mode: "shuttle",
      durationMinutes: 85,
      description: "BMTC Vayu Vajra Airport AC Express (KIA-9 to Majestic)",
      estCost: 260,
    },
    {
      fromNodeCode: "SBC",
      toNodeCode: "MJC",
      cityId: "BLR",
      mode: "walk",
      durationMinutes: 8,
      description: "Direct subterranean pedestrian skywalk between SBC Railway Station & Majestic Bus Stand",
      estCost: 0,
    },
  ],
  DEL: [
    {
      fromNodeCode: "DEL",
      toNodeCode: "NDLS",
      cityId: "DEL",
      mode: "metro",
      durationMinutes: 22,
      description: "Delhi Metro Airport Express Line (T3 to New Delhi Metro Station)",
      estCost: 60,
    },
    {
      fromNodeCode: "DEL",
      toNodeCode: "ISBT",
      cityId: "DEL",
      mode: "metro",
      durationMinutes: 40,
      description: "Airport Express to NDLS, transfer to Yellow Line to Kashmere Gate ISBT",
      estCost: 80,
    },
    {
      fromNodeCode: "NDLS",
      toNodeCode: "ISBT",
      cityId: "DEL",
      mode: "metro",
      durationMinutes: 16,
      description: "Delhi Metro Yellow Line (New Delhi to Kashmere Gate Station)",
      estCost: 30,
    },
  ],
  BOM: [
    {
      fromNodeCode: "BOM",
      toNodeCode: "CSMT",
      cityId: "BOM",
      mode: "cab",
      durationMinutes: 45,
      description: "Prepaid Taxi / Uber via Eastern Freeway",
      estCost: 450,
    },
    {
      fromNodeCode: "BOM",
      toNodeCode: "DDR",
      cityId: "BOM",
      mode: "cab",
      durationMinutes: 30,
      description: "Direct Cab/Auto via Western Express Highway",
      estCost: 280,
    },
    {
      fromNodeCode: "CSMT",
      toNodeCode: "DDR",
      cityId: "BOM",
      mode: "metro",
      durationMinutes: 20,
      description: "Mumbai Suburban Central Line Fast Local (CSMT to Dadar)",
      estCost: 15,
    },
  ],
  HYD: [
    {
      fromNodeCode: "HYD",
      toNodeCode: "SC",
      cityId: "HYD",
      mode: "shuttle",
      durationMinutes: 70,
      description: "TSRTC Pushpak Airport AC Liner (AC Express to Secunderabad)",
      estCost: 250,
    },
    {
      fromNodeCode: "HYD",
      toNodeCode: "MGBS",
      cityId: "HYD",
      mode: "shuttle",
      durationMinutes: 50,
      description: "TSRTC Pushpak Airport AC Liner to MGBS Imlibun Terminal",
      estCost: 200,
    },
    {
      fromNodeCode: "SC",
      toNodeCode: "MGBS",
      cityId: "HYD",
      mode: "metro",
      durationMinutes: 24,
      description: "Hyderabad Metro Green Line (Secunderabad West to MGBS Station)",
      estCost: 45,
    },
  ],
};

// Scoring weights by optimization mode
export interface ScoringWeights {
  priceWeight: number;
  timeWeight: number;
  reliabilityWeight: number;
  deadlineWeight: number;
  transferWeight: number;
}

export const OPTIMIZATION_WEIGHTS: Record<OptimizationMode, ScoringWeights> = {
  best_balance: {
    priceWeight: 0.25,
    timeWeight: 0.25,
    reliabilityWeight: 0.20,
    deadlineWeight: 0.20,
    transferWeight: 0.10,
  },
  cheapest: {
    priceWeight: 0.55,
    timeWeight: 0.15,
    reliabilityWeight: 0.10,
    deadlineWeight: 0.15,
    transferWeight: 0.05,
  },
  fastest: {
    priceWeight: 0.10,
    timeWeight: 0.50,
    reliabilityWeight: 0.15,
    deadlineWeight: 0.20,
    transferWeight: 0.05,
  },
  highest_confidence: {
    priceWeight: 0.10,
    timeWeight: 0.15,
    reliabilityWeight: 0.35,
    deadlineWeight: 0.30,
    transferWeight: 0.10,
  },
};
